version: "3.8"
services:
  proxy.envoy.localhost:
    image: envoyproxy/envoy:debug-dev-ad9b1cc9dc795f0243d1a85ec5ba0872173c9e42
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./envoy/cert.pem:/etc/cert.pem
      - ./envoy/key.pem:/etc/key.pem
    ports:
      - "80:8080"
      - "443:8443"
      - "9901:9901"
    command: ["-c", "/etc/envoy.yaml"]
